# -*- coding: utf-8 -*-
"""Assignment-01_iNeuron_Prog

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sI7CZ2UN5rkDP3TwMQhDFoWxgSGU7K84

**1. Write a Python program to print "Hello Python"?**
"""

print("Hello Python")

"""**2. Write a Python program to do arithmetical operations addition and division?**"""

num_1 = int(input("Enter the fist number: "))
num_2 = int(input("Enter the second number: "))

addition = num_1 + num_2
division = num_1 / num_2
rounded_result = round(division, 2)

print(f"The additon of two numbers: {addition}")
print(f"The division of two numbers: {rounded_result}")

"""**3. Write a Python program to find the area of a triangle?**"""

a = float(input("Enter the measure of 1st side: "))
b = float(input("Enter the measure of 2nd side: "))
c = float(input("Enter the measure of 3rd side: "))

s = (a + b + c)/2

area_of_traingle = (s*(s - a)*(s - b)*(s - c)) ** 0.5
print(f"The area of trangle is %0.2f" %area_of_traingle)

"""**4. Write a Python program to swap two variables?**"""

x = int(input("Enter the first number: "))
y = int(input("Enter the second number: "))

a = x
x = y
y = a

print(f"The value of x after swapping: ", x)
print(f"The value of y after swapping: ", y)

"""**5. Write a Python program to generate a random number?**"""

import random

print(random.randint(0,100))